disabled_rules: # rule identifiers to exclude from running
  - colon
  - line_length
  - cyclomatic_complexity
  - identifier_name
excluded:
  - Carthage
  - Pods
  - Mockingbird/Thirdparty
opt_in_rules:
  - closure_spacing

file_length:
  warning: 600
  error: 1000

function_parameter_count:
  warning: 8
  error: 10

function_body_length:
  warning: 120
  error: 200

number_separator:
  minimum_length: 5

identifier_name:
  min_length: 3 # only min_length
  error: 3 # only error
  excluded: # excluded via string array
    - id
    - in
    - URL

type_name:
  max_length: 50
