platform :osx, '10.13'

target 'Mockingbird' do
  use_frameworks!

  # Pods for Mockingbird
  pod 'Swifter', '~> 1.4.7'
  pod 'Zip', '~> 1.1.0'
  pod 'SwiftGui', '~> 0.9.2'
  pod 'ReSwift', '~> 5.0.0'
  pod 'Files', '~> 4.0.2'
  pod 'AppCenter', '~> 4.0.0'

  target 'MockingbirdTests' do
    inherit! :search_paths

    pod 'Starscream', '~> 4.0.4'
    
  end

  target 'MockingbirdUITests' do
  end

end
