name: Build Action
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dependencies
      working-directory: ./src
      run: pod install --repo-update

    - name: Build
      working-directory: ./src
      run: xcodebuild -workspace Mockingbird.xcworkspace build -scheme Mockingbird

    - name: Test
      working-directory: ./src
      run: xcodebuild -workspace Mockingbird.xcworkspace test -scheme Mockingbird '-only-testing:MockingbirdTests'